name: Deploy Python App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          pip install -r "Gemini Text Cleaner/requirements.txt"

      - name: Test Python file
        run: |
          python -m py_compile "text_cleaner.py"

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 3136
          script: |
            cd /home/dpd/Sinhala-text-cleaner-for-ASR-Chatbot-for-Caller-center
            git fetch origin
            git reset --hard origin/main
            git clean -fd
            pip install -r "Gemini Text Cleaner/requirements.txt"
            pkill -f "[t]ext_cleaner.py" || true
            nohup python text_cleaner.py >> app.log 2>&1 &
            sleep 3
            pgrep -af "[t]ext_cleaner.py" || true
